---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: async-batch-quickstart
  region: ap-northeast-1
  version: "1.27"

managedNodeGroups:
- name: managed-ng
  minSize: 3
  maxSize: 6
  desiredCapacity: 3
  instanceType: c5a.xlarge
  privateNetworking: true
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
    k8s.io/cluster-autoscaler/async-batch-quickstart: 'owned'

addons:
  - name: aws-efs-csi-driver
  
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
  - metadata:
      name: ecr-sa
      namespace: default
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser

cloudWatch:
 clusterLogging:
   enableTypes: ["*"]
   logRetentionInDays: 30