---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: async-batch-quickstart
  region: ap-northeast-1
  version: "1.27"

managedNodeGroups:
- name: managed-ng
  minSize: 1
  maxSize: 1
  desiredCapacity: 1
  instanceType: t3.small
  privateNetworking: true
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
    k8s.io/cluster-autoscaler/async-batch-quickstart: 'owned'

addons:
  - name: aws-efs-csi-driver
  
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: eks-exec-sa
      namespace: default
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
cloudWatch:
 clusterLogging:
   enableTypes: ["*"]
   logRetentionInDays: 30