apiVersion: batch/v1
kind: CronJob
metadata:
  name: new-batch-job
  namespace: default
spec:
  schedule: "35 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: eks-exec-sa
          containers:
          - name: batch-processor
            image: 321699386584.dkr.ecr.ap-northeast-1.amazonaws.com/batch-processing-repo:latest
            env:
              - name: AWS_REGION
                value: ap-northeast-1
          restartPolicy: OnFailure